"""Add middle name to users

Revision ID: 6c40fdb7a18c
Revises: b9c29c81d9f7
Create Date: 2026-03-28 15:31:29.472659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c40fdb7a18c'
down_revision: Union[str, Sequence[str], None] = 'b9c29c81d9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.String(), nullable=True))
    op.execute("UPDATE users SET middle_name = '' WHERE middle_name IS NULL")
    op.alter_column('users', 'middle_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###
